import { Widget, ExtensionComponent } from '@fleetbase/ember-core/contracts';

export default {
    setupExtension(app, universe) {
        const menuService = universe.getService('universe/menu-service');
        const widgetService = universe.getService('universe/widget-service');

        // Register header navigation
        menuService.registerHeaderMenuItem('Pallet', 'console.pallet', { icon: 'pallet', priority: 1, description: 'Warehouse and inventory management.', });

        // Register dashboard and widgets
        this.registerWidgets(widgetService);
    },

    registerWidgets(widgetService) {
        const kpiGridOptions = { w: 3, h: 4, minW: 3, minH: 4 };
        const pairedPanelGridOptions = { w: 6, h: 8, minW: 5, minH: 7 };
        const tallPanelGridOptions = { w: 6, h: 10, minW: 5, minH: 8 };

        const widgets = [
            new Widget({
                id: 'pallet-kpi-total-skus',
                name: 'Total SKUs',
                description: 'Total Pallet products and product variants tracked for inventory.',
                icon: 'boxes-stacked',
                component: new ExtensionComponent('@fleetbase/pallet-engine', 'widget/kpi-total-skus'),
                grid_options: kpiGridOptions,
                category: 'KPI Tiles',
                default: true,
            }),
            new Widget({
                id: 'pallet-kpi-available-units',
                name: 'Available Units',
                description: 'Inventory units available to promise.',
                icon: 'box-open',
                component: new ExtensionComponent('@fleetbase/pallet-engine', 'widget/kpi-available-units'),
                grid_options: kpiGridOptions,
                category: 'KPI Tiles',
                default: true,
            }),
            new Widget({
                id: 'pallet-kpi-reserved-units',
                name: 'Reserved Units',
                description: 'Inventory units committed to active reservations and fulfillment.',
                icon: 'lock',
                component: new ExtensionComponent('@fleetbase/pallet-engine', 'widget/kpi-reserved-units'),
                grid_options: kpiGridOptions,
                category: 'KPI Tiles',
                default: true,
            }),
            new Widget({
                id: 'pallet-kpi-stock-value',
                name: 'Stock Value',
                description: 'Total on-hand stock value across all warehouses.',
                icon: 'sack-dollar',
                component: new ExtensionComponent('@fleetbase/pallet-engine', 'widget/kpi-stock-value'),
                grid_options: kpiGridOptions,
                category: 'KPI Tiles',
                default: true,
            }),
            new Widget({
                id: 'pallet-kpi-low-stock',
                name: 'Low Stock',
                description: 'Inventory records at or below minimum quantity.',
                icon: 'triangle-exclamation',
                component: new ExtensionComponent('@fleetbase/pallet-engine', 'widget/kpi-low-stock'),
                grid_options: kpiGridOptions,
                category: 'KPI Tiles',
                default: true,
            }),
            new Widget({
                id: 'pallet-kpi-expiring-soon',
                name: 'Expiring Soon',
                description: 'Inventory lots expiring in the next 30 days.',
                icon: 'calendar-xmark',
                component: new ExtensionComponent('@fleetbase/pallet-engine', 'widget/kpi-expiring-soon'),
                grid_options: kpiGridOptions,
                category: 'KPI Tiles',
                default: true,
            }),
            new Widget({
                id: 'pallet-kpi-open-pos',
                name: 'Open POs',
                icon: 'file-invoice',
                description: 'Purchase orders still awaiting receipt.',
                component: new ExtensionComponent('@fleetbase/pallet-engine', 'widget/kpi-open-pos'),
                grid_options: kpiGridOptions,
                category: 'KPI Tiles',
                default: true,
            }),
            new Widget({
                id: 'pallet-kpi-open-fulfillment',
                name: 'Open Fulfillment',
                description: 'Active reservations, waves, and pick lists requiring execution.',
                icon: 'clipboard-list',
                component: new ExtensionComponent('@fleetbase/pallet-engine', 'widget/kpi-open-fulfillment'),
                grid_options: kpiGridOptions,
                category: 'KPI Tiles',
                default: true,
            }),
            new Widget({
                id: 'pallet-inventory-health',
                name: 'Inventory Health',
                description: 'In-stock, low-stock, out-of-stock, expired, and expiring inventory posture.',
                icon: 'heart-pulse',
                component: new ExtensionComponent('@fleetbase/pallet-engine', 'widget/inventory-health'),
                grid_options: pairedPanelGridOptions,
                category: 'Analytics',
                default: true,
            }),
            new Widget({
                id: 'pallet-warehouse-utilization',
                name: 'Warehouse Utilization',
                description: 'Inventory units, availability, and reservations by warehouse.',
                icon: 'warehouse',
                component: new ExtensionComponent('@fleetbase/pallet-engine', 'widget/warehouse-utilization'),
                grid_options: pairedPanelGridOptions,
                category: 'Analytics',
                default: true,
            }),
            new Widget({
                id: 'pallet-stock-movement',
                name: 'Stock Movement',
                description: 'Stock transaction volume by type over the recent operating period.',
                icon: 'arrow-trend-up',
                component: new ExtensionComponent('@fleetbase/pallet-engine', 'widget/stock-movement'),
                grid_options: pairedPanelGridOptions,
                category: 'Analytics',
                default: true,
            }),
            new Widget({
                id: 'pallet-fulfillment-workload',
                name: 'Fulfillment Workload',
                description: 'Reservations, waves, pick lists, cycle counts, and transfers grouped by status.',
                icon: 'clipboard-list',
                component: new ExtensionComponent('@fleetbase/pallet-engine', 'widget/fulfillment-workload'),
                grid_options: pairedPanelGridOptions,
                category: 'Operations',
                default: true,
            }),
            new Widget({
                id: 'pallet-reorder-risk',
                name: 'Reorder Risk',
                description: 'Products that have fallen at or below their reorder point.',
                icon: 'cart-flatbed',
                component: new ExtensionComponent('@fleetbase/pallet-engine', 'widget/reorder-risk'),
                grid_options: tallPanelGridOptions,
                category: 'Operations',
                default: true,
            }),
            new Widget({
                id: 'pallet-expiring-stock',
                name: 'Expiring Stock',
                description: 'Inventory batches that are expiring within the next 30 days',
                icon: 'calendar-xmark',
                component: new ExtensionComponent('@fleetbase/pallet-engine', 'widget/expiring-stock'),
                grid_options: tallPanelGridOptions,
                options: { title: 'Expiring Stock' },
                category: 'Operations',
                default: true,
            }),
            new Widget({
                id: 'pallet-stock-value',
                name: 'Stock Value by Warehouse',
                description: 'Total inventory value broken down per warehouse',
                icon: 'chart-bar',
                component: new ExtensionComponent('@fleetbase/pallet-engine', 'widget/stock-value'),
                grid_options: pairedPanelGridOptions,
                options: { title: 'Stock Value by Warehouse' },
                category: 'Legacy',
                default: false,
            }),

            new Widget({
                id: 'pallet-low-stock',
                name: 'Low Stock Alerts',
                description: 'Products that have fallen at or below their minimum stock threshold',
                icon: 'triangle-exclamation',
                component: new ExtensionComponent('@fleetbase/pallet-engine', 'widget/low-stock'),
                grid_options: pairedPanelGridOptions,
                options: { title: 'Low Stock Alerts' },
                category: 'Legacy',
                default: false,
            }),

            new Widget({
                id: 'pallet-top-products',
                name: 'Top Products by Movement',
                description: 'Most frequently moved products based on stock transactions',
                icon: 'arrow-trend-up',
                component: new ExtensionComponent('@fleetbase/pallet-engine', 'widget/top-products'),
                grid_options: pairedPanelGridOptions,
                options: { title: 'Top Products by Movement' },
                category: 'Operations',
                default: true,
            }),
            new Widget({
                id: 'pallet-po-status',
                name: 'Purchase Order Status',
                description: 'Breakdown of purchase orders by status - pending, partially received, and fully received',
                icon: 'truck-ramp-box',
                component: new ExtensionComponent('@fleetbase/pallet-engine', 'widget/po-status'),
                grid_options: pairedPanelGridOptions,
                options: { title: 'Purchase Order Status' },
                category: 'Legacy',
                default: false,
            }),
            new Widget({
                id: 'pallet-so-status',
                name: 'Sales Order Status',
                description: 'Breakdown of sales orders by status - pending, partially fulfilled, and fully fulfilled',
                icon: 'file-invoice',
                component: new ExtensionComponent('@fleetbase/pallet-engine', 'widget/so-status'),
                grid_options: pairedPanelGridOptions,
                options: { title: 'Sales Order Status' },
                category: 'Legacy',
                default: false,
            }),
            new Widget({
                id: 'pallet-recent-activity',
                name: 'Recent Activity',
                description: 'Latest operational audit trail events - stock adjustments, receipts, fulfillments, and cycle counts',
                icon: 'clock-rotate-left',
                component: new ExtensionComponent('@fleetbase/pallet-engine', 'widget/recent-activity'),
                grid_options: pairedPanelGridOptions,
                options: { title: 'Recent Activity' },
                category: 'Operations',
                default: true,
            }),
            new Widget({
                id: 'pallet-inventory-summary',
                name: 'Inventory Summary (Legacy)',
                description: 'Legacy grouped inventory summary. Replaced by individual Pallet KPI tiles.',
                icon: 'boxes-stacked',
                component: new ExtensionComponent('@fleetbase/pallet-engine', 'widget/inventory-summary'),
                grid_options: { w: 12, h: 6, minW: 8, minH: 5 },
                options: { title: 'Inventory Summary' },
                category: 'Legacy',
                default: false,
            }),
        ];

        widgetService.registerDashboard('pallet');
        widgetService.registerWidgets('pallet', widgets);
    },
};
