linkWorkspacePackages: deep
preferWorkspacePackages: true
publicHoistPattern:
  - "*ember-core*"
  - "*ember-ui*"
  - "*fleetops-data*"
overrides:
  "@gridx/fleetops-data": "^0.1.40"
  "@gridx/ember-core": "^0.3.24"
  "@gridx/ember-ui": "^0.3.41"
allowBuilds:
  "@fortawesome/fontawesome-common-types": false
  "@fortawesome/fontawesome-svg-core": false
  "@fortawesome/free-brands-svg-icons": false
  "@fortawesome/free-solid-svg-icons": false
  core-js: false
  fsevents: false
